-- CATEGORÍAS DE PRODUCTOS
CREATE TABLE CATEGORIES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL UNIQUE,
  DESCRIPTION TEXT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- PRODUCTOS
CREATE TABLE PRODUCTS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION TEXT,
  PRICE DECIMAL(10,2) NOT NULL,
  IMAGE VARCHAR(255),
  STOCK INT NOT NULL DEFAULT 0,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  IS_FEATURED BOOLEAN DEFAULT FALSE,
  TIMES_PURCHASED DECIMAL(5,2) DEFAULT 0,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CATEGORY_ID INT,
  FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
);

-- USUARIOS
CREATE TABLE USERS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(50) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL UNIQUE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- COMPRAS (cada compra tiene un usuario y fecha)
CREATE TABLE PURCHASES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID INT NOT NULL,
  TOTAL DECIMAL(10,2),
  PURCHASE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- DETALLE DE CADA COMPRA (productos comprados en cada compra)
CREATE TABLE PURCHASE_ITEMS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  PURCHASE_ID INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  QUANTITY INT NOT NULL,
  FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASES(ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

-- RESEÑAS DE PRODUCTOS
CREATE TABLE REVIEWS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID INT NOT NULL,
  USER_ID INT NOT NULL,
  RATING INT CHECK (RATING >= 1 AND RATING <= 5),
  COMMENT TEXT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

