CREATE TABLE PRODUCTS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  PRICE DECIMAL(10,2) NOT NULL,
  IMAGE_URL VARCHAR(255)
);

CREATE TABLE CART_ITEMS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID INT NOT NULL,
  QUANTITY INT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

CREATE TABLE PURCHASES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID INT NOT NULL,
  QUANTITY INT NOT NULL,
  PURCHASE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);